Documentation:
  Enabled: false
Rails:
  Enabled: true
Style/FrozenStringLiteralComment:
  Enabled: false
AllCops:
  UseCache: false
  TargetRubyVersion: 2.3
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
    - 'spec/features/user/*'
    - 'spec/features/visitor/*'
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'scenario', 'let']